# Creating Array using numpy

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[1])

2


In [2]:
print(a[4])

5


In [3]:
#adding/subtraction/division/multiplicatiopn
print(a[1]+a[4])

7


In [5]:
#accessing elements in 2D array
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(b[0,1]) #it means second element of the first row
print(b[1,0]) #it means first element of the second row

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
6


In [9]:
#accessing elements in 3D array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c[0,1,2]) #it will print 6 
print(c[1,0,1]) #it will print 8

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
8
