# Copy and View Function

In [ ]:
# learning copy and view in numpy
#! copy feature makes the copy of the original array, any change in the copied array will not affect
#! the original array.

#* in view feature, vice versa of copy feature, any change in array will affect the original array

In [3]:
#copy feature

import numpy as np
x1=np.array([1,2,3,4,5])
x2=x1.copy()
x2[0]=10
print(x1)
print(x2)

[1 2 3 4 5]
[10  2  3  4  5]


In [4]:
#view feature

x3=np.array([1,2,3,4,5])
x4=x3.view()
x3[0]=43

print(x3)
print(x4)

#! changing original aray is also effecting the viewd array

[43  2  3  4  5]
[43  2  3  4  5]
