# Datatypes in numpy

In [ ]:
# numpy array datatypes
#! data types in python: str,int,boolean,complex,float
#* data types in numpy:
#? > i for integer
#? > b for boolean 
#? > u for unsgned integer
#? > f for float
#? > c for complex float
#? > m for timedelta
#? > M for datetime
#? > O for object
#? > S for string 
#? > U for unicode-string
#? > V -memory

In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a.dtype)

int64


In [4]:
b=np.array(["apple","banana","cherry"])
print(b.dtype)

<U6


In [5]:
c=np.array([1,2,3,4], dtype="S")
print(c)
print(c.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [7]:
#converting array data types using dtype feature
d=np.array([1,2,3,4],dtype="i4")
print(d)
print(d.dtype)

[1 2 3 4]
int32


In [7]:
import numpy as np
e=np.zeros((4,6))
print(e)
print(e.dtype)
print(e.ndim)
#? [np.zeros(rows,column)] will create an array of 0's providing rows and column strength

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
float64
2


In [8]:
f=np.array(["a","2","3"], dtype="i")
print(f)

#! converting the string data type into integer
#! it will show error as "a" is not an integer

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#! converting float datatype into integer
#! using astype feature which creates a copy of the array and makes changes in copied array

x1=np.array([1.1,2.3,3.4])
x2=x1.astype("i")
print(x2)
print(x2.dtype)

[1 2 3]
int32


In [ ]:
#converting integer datatype into boolean
x3=np.array([1,0])
x4=x3.astype(bool)
print(x4)
print(x4.dtype)

[ True False]
bool
