In [ ]:
# Filtering()
#? getting some elements out of an existing array and creating a new array is called filtering 

In [1]:
import numpy as np
x1=np.array([31,32,33,34,35,36,37,38])
x2=[True,False,True,False,True,True,False,False]
x3=x1[x2]
print(x3)

[31 33 35 36]


In [4]:
x4=np.array([31,32,33,34,35,36,37,38])
x5=[]
for elements in x4:
    if elements>34:
        x5.append(True)
    else:
        x5.append(False)
x6=x4[x5]
print(x5)
print(x6)

#? filtering an array using for loop

[False, False, False, False, True, True, True, True]
[35 36 37 38]


In [5]:
x4=np.array([31,32,33,34,35,36,37,38])
x5=[]
for elements in x4:
    if elements%2==0:
        x5.append(True)
    else:
        x5.append(False)
x6=x4[x5]
print(x5)
print(x6)

[False, True, False, True, False, True, False, True]
[32 34 36 38]


In [9]:
y1=np.array({41,42,43,44,45,46})
y2=y1 > 42
y3=y1[y2]
print(y2)
print(y3)

TypeError: '>' not supported between instances of 'set' and 'int'