# Array Index/Slicing using numpy

In [3]:
#Topic-slicing index
#slicing means taking elements from one given index to another index
#[start:end] or [start:end:step]

import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10])
print(x[1:5])
print(x[0:6])

# [0:6] means it will start from 1 and end on "5"
# [1:5] means it will start from "2" and end on "4"

[2 3 4 5]
[1 2 3 4 5 6]


In [5]:
#steps: are used to determine the step valuen of the array 
y=np.array([1,2,3,4,5,6,7,8,9])
print(y[1:6:2])

[2 4 6]


In [23]:
#slicing with steps on 2D array
z=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#to print 7,8,9
print(z[1,1:4])

print(z[0:2,1:4])

[7 8 9]
[[2 3 4]
 [7 8 9]]
