# Arrays joining

In [3]:
#! joining the arrays usding concatenate() function
import numpy as np
x1=np.array([1,2,3])
x2=np.array([4,5,6])
x=np.concatenate((x1,x2))
print(x)



[1 2 3 4 5 6]


In [5]:
#joining the 2D arrays along with axis=1

x3=np.array([[1,2],[3,4]])
x4=np.array([[5,6],[7,8]])
x=np.concatenate((x3,x4),axis=1)
print(x)

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
#joining arrays using stack function
x5=np.array([1,2,3])
x6=np.array([4,5,6])
x=np.stack((x5,x6),axis=1)
print(x)

[[1 4]
 [2 5]
 [3 6]]


In [8]:
#stacking along with rows
x5=np.array([1,2,3])
x6=np.array([4,5,6])
x=np.hstack((x5,x6))
print(x)

#! hstack(): used for row stacking


[1 2 3 4 5 6]


In [9]:
#stacking along with columns: vstack()
x5=np.array([1,2,3])
x6=np.array([4,5,6])
x=np.vstack((x5,x6))
print(x)

#! vstack(): used for column stacking 

[[1 2 3]
 [4 5 6]]
