# Matrix Funtions in numpy

- Transpose
- Swapaxes
- Inverse
- Power
- Determinate

## Transpose

In [2]:
import numpy as np
var=np.array([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


## Swapaxes

In [4]:
x1=np.array([[1,2,3],[4,5,6]])
print(x1)
print(np.swapaxes(x1,0,1))
print()
x2=np.array([[1,2],[3,4]])
print(x2)
print(np.swapaxes(x2,0,1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


## Inverse
- np.linalg.inv(array)

In [5]:
x1=np.array([[1,2],[3,4]])
print(x1)
print(np.linalg.inv(x1))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


## Power
- np.linalg.matrix_power(array,power)

In [6]:
x1=np.array([[1,2],[3,4]])
print(x1)
print()
print(np.linalg.matrix_power(x1,2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]
