In [5]:
# Random - soimething that cannot be predicted logically
from numpy import random
x=random.randint(100)
print(x)

#! everytime it will gwenerate random number from 1 to 100


73


In [11]:
x=random.rand()
print(x)

# everytime it will generate random numbers between 0 and 1

0.35179719242574914


In [15]:
x=random.randint(100,size=(10))
print(x)

#! size=(5) determines the no.of elements in an array
# it will create an 1D array of 10 random number from 0 to 100

[ 7 57 42  0 15 74 88 46 14 93]


In [18]:
x=random.randint(100, size=(3,5))
print(x)

#! it will create an 2D array - having 3 array each containing 5 elements  

[[23 56 45 56 16]
 [57 42 31 20 98]
 [24 18 43 15  9]]


In [19]:
x=random.rand(3,5)
print(x)

[[0.75410592 0.45065617 0.51429587 0.83118351 0.98872254]
 [0.12214118 0.49481275 0.56481878 0.46783824 0.21014837]
 [0.88026684 0.22242985 0.31445027 0.43060817 0.83728652]]


In [22]:
x=random.choice([1,2,3,4,5,6,7,8])
print(x)

#! it will choose an random no. from the given array

2


In [24]:
x=random.choice([1,2,3,4,5,6,7,8,9], size=(3,5))
print(x)

#this code will create a 2d array of 3 array and 5 elements by randomly choosing elements from given array

[[8 4 2 2 2]
 [3 4 5 4 9]
 [3 8 6 6 9]]
