# Array Reshaping

In [ ]:
# Array Reshaping
#! Reshaping means changing the elements like removing or adding elements

In [1]:
# Reshaping from 1D to 2D
import numpy as np
x1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x2=x1.reshape(4,3)
print(x2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
x3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x4=x3.reshape(2,3,2)
print(x4)
print(x4.ndim)

#! converting 1D array into 3D array using reshape function
#? .reshape(indexing,no. of elements)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [4]:
#unknown dimension
#* only one unknown dimension is allowed by passing -1

x5=np.array([1,2,3,4,5,6,7,8])
x6=x5.reshape(2,2,-1)
print(x6)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#converting a mulit dimension array into 1D array
x7=np.array([[1,2,3],[4,5,6]])
x8=x7.reshape(-1)
print(x8)

#? there are many functions in numpy to change the shapes of an array in numpy 
#* like- flattern, ravel etc.
#* for rearranging the elements- rot90, flip, fliplr, flipud
#! all these functions comes under advance numpy 

[1 2 3 4 5 6]
