In [1]:
#Sort function
#! it will the array the array in ascending or descending order numerical or alphabetical etc.

import numpy as np
x1=np.array([2,1,5,9,7,90,44,23,4,6])
print(np.sort(x1))

[ 1  2  4  5  6  7  9 23 44 90]


In [2]:
x2=np.array(["b","d","a","c","f","e"])
print(np.sort(x2))

['a' 'b' 'c' 'd' 'e' 'f']


In [3]:
#sorting the boolean array
x3=np.array([True,True,False])
print(np.sort(x3))


[False  True  True]


In [5]:
#sorting the 2D array
x4=np.array([[4,3,2],[6,0,4]])
print(np.sort(x4))


[[2 3 4]
 [0 4 6]]
